export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAILED = 'FETCH_COUNTRY_FAILED';

export const SORT_CITY_ASC = 'SORT_CITY_ASC';
export const SORT_CITY_DESC = 'SORT_CITY_DESC';

export const SEARCH_CITY = 'SEARCH_CITY';
